services:
  gateway:
    image: ghcr.io/taiters/gateway:${VERSION}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gateway

networks:
  gateway:
    name: gateway