name: "Build and deploy"
on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Write certs
        shell: bash
        run: |
          echo "$SECRET_COUP_ORIGIN_KEY" > ./config/ssl/coup.dotslashdan.com.key
          echo "$SECRET_COUP_ORIGIN_CERT" > ./config/ssl/coup.dotslashdan.com.crt
          echo "TEST" > ./config/ssl/sometestfile.txt
          echo "TEST" > ./config/ssl/sometestdanfile.txt
        env:
          SECRET_COUP_ORIGIN_KEY: "${{ secrets.COUP_ORIGIN_PRIVATE_KEY }}"
          SECRET_COUP_ORIGIN_CERT: "${{ secrets.COUP_ORIGIN_CERTIFICATE }}"

      - name: Build and push gateway
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/taiters/gateway:latest
            ghcr.io/taiters/gateway:${{ github.run_number }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SECRET_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SECRET_SERVER_IP >> ~/.ssh/known_hosts
        env:
          SECRET_SSH_KEY: "${{ secrets.SSH_KEY }}"
          SECRET_SERVER_IP: "${{ secrets.SERVER_IP }}"
      
      - name: Deploy
        run: |
          scp docker-compose.yml $SECRET_SERVER_USER@$SECRET_SERVER_IP:~/gateway/docker-compose.yml
          ssh $SECRET_SERVER_USER@$SECRET_SERVER_IP "cd ~/gateway && VERSION=${{ github.run_number }} docker compose up -d"
        env:
          SECRET_SERVER_USER: "${{ secrets.SERVER_USER }}"
          SECRET_SERVER_IP: "${{ secrets.SERVER_IP }}"